import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'uk' | 'es' | 'de' | 'nl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  translations: Record<string, string>;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// all translations
const allTranslations: Record<Language, Record<string, string>> = {
  en: {
    homePage: 'Home',
    servicesPage: 'Services',
    teamPage: 'Our Team',
    contactPage: 'Contact',
    
    companyTagline: 'Innovating Digital Solutions',
    freePartLine1: 'Flexible Software ',
    freePartLine2: 'Solutions for Modern Needs',
    weArePart: 'We are RZK Soft, a flexible collective of developers and designers. We don\'t just assign \"anyone\" to your project — we bring together the specific experts needed to build your unique solution',
    hireUsPart: 'Hire us',
    firstPartOfBodySecondaryTextPage: 'Our company specializes in providing high-quality software development and design services.',
    ourServicespage: 'Our Services',
    webDevelopmentPage: 'Web Development',
    designPage: 'UI/UX Design',
    mobilePage: 'Mobile Development',
    brandingPage: 'Branding',
    aiMlPage: "AI & Machine Learning",
    devOpsPage: "DevOps & Cloud",
    consultingPage: "Tech Consulting",
    maintenancePage: 'Maintenance & Support',
    viewFullProfile: 'View Full Profile',
    techStack: 'Tech Stack',
    projects: 'Projects',
    support: 'Support',
    satisfaction: 'Satisfaction', 
    yearsExperience: 'Years of Experience',
    diplomasAwards: 'Diplomas & Awards',
    viewCertificate: 'View Certificate',
    viewOnGitHub: 'View on GitHub',
    quickLinks: 'Quick Links',
    contactUs: 'Contact Us',
    followUs: 'Follow Us',
    // about
    aboutUsPage: "About Us",
    aboutText: "RZK Soft operates as a Dynamic Expert Collective. Instead of maintaining a rigid, generalist staff, we curate a flexible squad of top-tier specialists for every project. Whether you need an AI architect, a mobile virtuoso, or a game design visionary, we bring the exact expertise required to your table.",
    missionTitle: "Our Mission",
    missionText: "To build impactful digital products by matching specialized expertise with unique business challenges.",
    visionTitle: "Our Vision",
    visionText: "To be the most reliable, expert-driven collective for building high-performance digital solutions without the overhead of a traditional agency.",
    valuesTitle: "Our Values",
    valuesText: "Quality, Innovation, Integrity, and Client Success are at the core of everything we do.",

    // services  our process
    ourProcess: "Our Process",
    discoveryTitle: "Discovery & Planning",
    discoveryText: "Understand requirements and create roadmap",
    designTitle: "Design & Prototyping",
    designText: "Create wireframes and design prototypes",
    developmentTitle: "Development",
    developmentText: "Code implementation with agile methodology",
    testingTitle: "Testing & Deployment",
    testingText: "Quality assurance and production launch",
    // about  why choose
    whyChooseTitle: "Why Choose RZK Soft?",
    whyChoose1: "Hand-picked specialist teams",
    whyChoose2: "Flexible on-demand scaling",
    whyChoose3: "Advanced AI & deep-tech focus",
    whyChoose4: "Intuitive design for complex systems",
    whyChoose5: "Direct developer-to-client contact",

    // services  looking for more
    lookingForMore: "Looking for something specific?",
    contactDesc: "We also specialize in custom solutions. Contact us to discuss your specific requirements.",
    getInTouch: "Get in Touch",

    meetOurTeam: "Meet Our Team",
    meetOurTeamDesc: "Our talented team of developers, designers, and strategists working together to deliver exceptional results.",
    
    rights: "All rights reserved",
    footerDesc: "Delivering exceptional software development and design solutions with cutting-edge technology and creative expertise.",
    builtWith: "Built with ❤️ using React, TypeScript & Tailwind CSS",

    filterAll: "All",
    filterDevelopers: "Developers",
    filterDesigners: "Designers",
    filterManagement: "Management",
    viewAllTeam: "View Full Team",

    required: "Required",
    messageSent: "Message sent successfully!",
    sendingError: "Error sending message. Please try again.",
    sending: "Sending...",


    newsPage: 'News',
    newsPageDesc: 'Stay updated with the latest news, announcements, and updates from RZK Soft.',
    readMore: 'Read More',
    backToNews: 'Back to News',
    publishedDate: 'Published',
    readTime: 'min read',
    by: 'By',
    category: 'Category',
    tags: 'Tags',
    allNews: 'All News',
    companyNews: 'Company News',
    technologyNews: 'Technology',
    teamUpdates: 'Team',
    tutorials: 'Tutorials',
    caseStudies: 'Case Studies',
    events: 'Events',
    filterByCategory: 'Filter by Category',
    searchNews: 'Search news...',
    noNewsFound: 'No news articles found.',
    shareArticle: 'Share Article',
    relatedArticles: 'Related Articles',
    viewAllNews: 'View All News'
    
  },
  uk: {
    homePage: 'Головна',
    aboutUsPage: 'Про нас',
    servicesPage: 'Послуги',
    teamPage: 'Наша команда',
    contactPage: 'Контакти',
    companyTagline: 'Інноваційні цифрові рішення',
    freePartLine1: 'Фріланс Розробка',
    freePartLine2: 'ПО та Дизайн',
    weArePart: 'Ми RZK Soft, команда досвідчених програмістів та дизайнерів',
    hireUsPart: 'Найняти нас',
    firstPartOfBodySecondaryTextPage: 'Наша компанія спеціалізується на наданні високоякісних послуг',
    ourServicespage: 'Наші послуги',
    webDevelopmentPage: 'Веб-розробка',
    designPage: 'UI/UX Дизайн',
    mobilePage: 'Мобільна розробка',
    brandingPage: 'Брендинг',
    aiMlPage: "ШІ та Машинне навчання",
    devOpsPage: "DevOps та Хмара",
    consultingPage: "Технологічний консалтинг",
    maintenancePage: "Обслуговування та підтримка",
    viewFullProfile: 'Переглянути профіль',
    techStack: 'Технології',
    projects: 'Проєкти',
    support: 'Підтримка',
    satisfaction: 'Задоволення клієнта', 
    yearsExperience: 'Років досвіду',
    diplomasAwards: 'Дипломи та нагороди',
    viewCertificate: 'Переглянути сертифікат',
    viewOnGitHub: 'Переглянути на GitHub',
    quickLinks: 'Швидкі посилання',
    contactUs: 'Контакти',

    followUs: 'Слідкуйте за нами',
    aboutText: "RZK Soft - це динамічна агенція з розробки програмного забезпечення, яка спеціалізується на створенні індивідуальних рішень для бізнесів будь-якого розміру. Маючи експертизу в сучасних технологіях та пристрасть до інновацій, ми перетворюємо ідеї на потужні цифрові досвіди.",
    missionTitle: "Наша Місія",
    missionText: "Надавати інноваційні програмні рішення, які дозволяють бізнесам та приватним особам досягати своїх цілей за допомогою передових технологій.",
    visionTitle: "Наше Бачення",
    visionText: "Стати провідним глобальним постачальником послуг з розробки програмного забезпечення, відомим завдяки якості, інноваціям та задоволенню клієнтів.",
    valuesTitle: "Наші Цінності",
    valuesText: "Якість, Інновації, Чесність та Успіх клієнта знаходяться в основі всього, що ми робимо.",

    ourProcess: "Наш процес",
    discoveryTitle: "Дослідження та Планування",
    discoveryText: "Збір вимог та створення дорожньої карти",
    designTitle: "Дизайн та Прототипування",
    designText: "Створення вайрфреймів та прототипів",
    developmentTitle: "Розробка",
    developmentText: "Реалізація коду за гнучкою методологією",
    testingTitle: "Тестування та Розгортання",
    testingText: "Забезпечення якості та запуск у продакшн",

    whyChooseTitle: "Чому обрати RZK Soft?",
    whyChoose1: "Експертна команда з різноманітними навичками",
    whyChoose2: "Передовий технологічний стек",
    whyChoose3: "Гнучка методологія розробки",
    whyChoose4: "Прозора комунікація",
    whyChoose5: "Конкурентні ціни",

    lookingForMore: "Шукаєте щось конкретне?",
    contactDesc: "Ми також спеціалізуємося на індивідуальних рішеннях. Зв'яжіться з нами, щоб обговорити ваші конкретні вимоги.",
    getInTouch: "Зв'яжіться з нами",

    meetOurTeam: "Наша команда",
    meetOurTeamDesc: "Наша талановита команда розробників, дизайнерів та стратегів працює разом, щоб досягати виняткових результатів.",
    rights: "Всі права захищені",
    footerDesc: "Ми надаємо виняткові рішення з розробки програмного забезпечення та дизайну, використовуючи передові технології та креативний підхід.",
    builtWith: "Створено з ❤️ за допомогою React, TypeScript та Tailwind CSS",

    filterAll: "Всі",
    filterDevelopers: "Розробники",
    filterDesigners: "Дизайнери",
    filterManagement: "Менеджмент",
    viewAllTeam: "Переглянути всю команду",
    required: "Обов'язково",
    messageSent: "Повідомлення успішно надіслано!",
    sendingError: "Помилка надсилання повідомлення. Спробуйте ще раз.",
    sending: "Надсилання...",

    newsPage: 'Новини',
    newsPageDesc: 'Будьте в курсі останніх новин, анонсів та оновлень від RZK Soft.',
    readMore: 'Читати далі',
    backToNews: 'Назад до новин',
    publishedDate: 'Опубліковано',
    readTime: 'хв читання',
    by: 'Від',
    category: 'Категорія',
    tags: 'Теги',
    allNews: 'Всі новини',
    companyNews: 'Новини компанії',
    technologyNews: 'Технології',
    teamUpdates: 'Команда',
    tutorials: 'Туторіали',
    caseStudies: 'Кейс стаді',
    events: 'Події',
    filterByCategory: 'Фільтрувати за категорією',
    searchNews: 'Пошук новин...',
    noNewsFound: 'Новини не знайдені.',
    shareArticle: 'Поділитися статтею',
    relatedArticles: 'Схожі статті',
    viewAllNews: 'Дивитися всі новини',
  },
  es: {
    homePage: 'Inicio',
    aboutUsPage: 'Sobre nosotros',
    servicesPage: 'Servicios',
    teamPage: 'Nuestro equipo',
    contactPage: 'Contacto',
    companyTagline: 'Innovando Soluciones Digitales',
    freePartLine1: 'Desarrollo Freelance',
    freePartLine2: 'Software y Diseño',
    weArePart: 'Somos RZK Soft, un equipo de programadores y diseñadores listos para ofrecer soluciones de primera calidad',
    hireUsPart: 'Contrátanos',
    firstPartOfBodySecondaryTextPage: 'Nuestra empresa se especializa en ofrecer servicios de desarrollo y diseño de software de alta calidad.',
    ourServicespage: 'Nuestros servicios',
    webDevelopmentPage: 'Desarrollo web',
    designPage: 'Diseño UI/UX',
    mobilePage: 'Desarrollo móvil',
    brandingPage: 'Branding',
    aiMlPage: "IA y Aprendizaje Automático",
    devOpsPage: "DevOps y Cloud",
    consultingPage: "Consultoría Tecnológica",
    maintenancePage: "Mantenimiento y Soporte",
    viewFullProfile: 'Ver perfil completo',
    techStack: 'Tecnologías',
    projects: 'Proyectos',
    support: 'Soporte',
    satisfaction: 'Satisfacción', 
    yearsExperience: 'Años de experiencia',
    diplomasAwards: 'Diplomas y premios',
    viewCertificate: 'Ver certificado',
    viewOnGitHub: 'Ver en GitHub',
    quickLinks: 'Enlaces rápidos',
    contactUs: 'Contáctanos',
    followUs: 'Síguenos',

    aboutText: "RZK Soft es una agencia dinámica de desarrollo de software especializada en crear soluciones personalizadas para empresas de todos los tamaños. Con experiencia en tecnologías modernas y pasión por la innovación, transformamos ideas en poderosas experiencias digitales.",
    missionTitle: "Nuestra Misión",
    missionText: "Entregar soluciones de software innovadoras que empoderen a empresas e individuos para alcanzar sus objetivos a través de tecnología de vanguardia.",
    visionTitle: "Nuestra Visión",
    visionText: "Convertirnos en un proveedor global líder de servicios de desarrollo de software, conocido por la excelencia, innovación y satisfacción del cliente.",
    valuesTitle: "Nuestros Valores",
    valuesText: "Calidad, Innovación, Integridad y Éxito del Cliente están en el centro de todo lo que hacemos.",

    ourProcess: "Nuestro Proceso",
    discoveryTitle: "Descubrimiento y Planificación",
    discoveryText: "Comprender requisitos y crear hoja de ruta",
    designTitle: "Diseño y Prototipado",
    designText: "Crear wireframes y prototipos de diseño",
    developmentTitle: "Desarrollo",
    developmentText: "Implementación de código con metodología ágil",
    testingTitle: "Pruebas y Despliegue",
    testingText: "Garantía de calidad y lanzamiento en producción",

    whyChooseTitle: "¿Por qué elegir RZK Soft?",
    whyChoose1: "Equipo experto con diversas habilidades",
    whyChoose2: "Stack tecnológico de vanguardia",
    whyChoose3: "Metodología ágil de desarrollo",
    whyChoose4: "Comunicación transparente",
    whyChoose5: "Precios competitivos",

    lookingForMore: "¿Buscas algo específico?",
    contactDesc: "También nos especializamos en soluciones personalizadas. Contáctanos para discutir tus requisitos específicos.",
    getInTouch: "Ponte en Contacto",

    meetOurTeam: "Conoce a Nuestro Equipo",
    meetOurTeamDesc: "Nuestro talentoso equipo de desarrolladores, diseñadores y estrategas trabaja en conjunto para ofrecer resultados excepcionales.",
    rights: "Todos los derechos reservados",
    footerDesc: "Ofrecemos soluciones excepcionales de desarrollo de software y diseño con tecnología de vanguardia y experiencia creativa.",
    builtWith: "Construido con ❤️ usando React, TypeScript y Tailwind CSS",

    filterAll: "Todos",
    filterDevelopers: "Desarrolladores",
    filterDesigners: "Diseñadores",
    filterManagement: "Gestión",
    viewAllTeam: "Ver Todo el Equipo",

    required: "Obligatorio",
    messageSent: "¡Mensaje enviado con éxito!",
    sendingError: "Error al enviar el mensaje. Por favor, inténtalo de nuevo.",
    sending: "Enviando...",


    newsPage: 'Noticias',
    newsPageDesc: 'Mantente al día con las últimas noticias, anuncios y actualizaciones de RZK Soft.',
    readMore: 'Leer más',
    backToNews: 'Volver a noticias',
    publishedDate: 'Publicado',
    readTime: 'min de lectura',
    by: 'Por',
    category: 'Categoría',
    tags: 'Etiquetas',
    allNews: 'Todas las noticias',
    companyNews: 'Noticias de la empresa',
    technologyNews: 'Tecnología',
    teamUpdates: 'Equipo',
    tutorials: 'Tutoriales',
    caseStudies: 'Casos de estudio',
    events: 'Eventos',
    filterByCategory: 'Filtrar por categoría',
    searchNews: 'Buscar noticias...',
    noNewsFound: 'No se encontraron artículos.',
    shareArticle: 'Compartir artículo',
    relatedArticles: 'Artículos relacionados',
    viewAllNews: 'Ver todas las noticias',
  },
  de: {
    homePage: 'Startseite',
    aboutUsPage: 'Über uns',
    servicesPage: 'Dienstleistungen',
    teamPage: 'Unser Team',
    contactPage: 'Kontakt',
    companyTagline: 'Innovative digitale Lösungen',
    freePartLine1: 'Freelance Software',
    freePartLine2: 'Entwicklung & Design',
    weArePart: 'Wir sind RZK Soft, ein Team erfahrener Programmierer und Designer, bereit erstklassige Lösungen zu liefern',
    hireUsPart: 'Engagieren Sie uns',
    firstPartOfBodySecondaryTextPage: 'Unser Unternehmen ist auf hochwertige Softwareentwicklung und Design spezialisiert.',
    ourServicespage: 'Unsere Dienstleistungen',
    webDevelopmentPage: 'Webentwicklung',
    designPage: 'UI/UX Design',
    mobilePage: 'Mobile Entwicklung',
    brandingPage: 'Branding',
    aiMlPage: "KI & Maschinelles Lernen",
    devOpsPage: "DevOps & Cloud",
    consultingPage: "Technologieberatung",
    maintenancePage: "Wartung & Support",
    viewFullProfile: 'Vollständiges Profil ansehen',
    techStack: 'Technologien',
    projects: 'Projekte',
    support: 'Support',
    satisfaction: 'Zufriedenheit', 
    yearsExperience: 'Jahre Erfahrung',
    diplomasAwards: 'Diplome & Auszeichnungen',
    viewCertificate: 'Zertifikat ansehen',
    viewOnGitHub: 'Auf GitHub ansehen',
    quickLinks: 'Schnellzugriff',
    contactUs: 'Kontaktieren Sie uns',
    followUs: 'Folgen Sie uns',

    aboutText: "RZK Soft ist eine dynamische Softwareentwicklungsagentur, die sich auf maßgeschneiderte Lösungen für Unternehmen jeder Größe spezialisiert hat. Mit Expertise in modernen Technologien und Leidenschaft für Innovation verwandeln wir Ideen in kraftvolle digitale Erlebnisse.",
    missionTitle: "Unsere Mission",
    missionText: "Innovative Softwarelösungen zu liefern, die Unternehmen und Einzelpersonen befähigen, ihre Ziele durch modernste Technologie zu erreichen.",
    visionTitle: "Unsere Vision",
    visionText: "Ein führender globaler Anbieter von Softwareentwicklungsdiensten zu werden, bekannt für Exzellenz, Innovation und Kundenzufriedenheit.",
    valuesTitle: "Unsere Werte",
    valuesText: "Qualität, Innovation, Integrität und Kundenerfolg stehen im Mittelpunkt all unseres Handelns.",

    ourProcess: "Unser Prozess",
    discoveryTitle: "Entdeckung & Planung",
    discoveryText: "Anforderungen verstehen und Fahrplan erstellen",
    designTitle: "Design & Prototyping",
    designText: "Wireframes und Designprototypen erstellen",
    developmentTitle: "Entwicklung",
    developmentText: "Code-Implementierung mit agiler Methodik",
    testingTitle: "Testen & Bereitstellung",
    testingText: "Qualitätssicherung und Produktionsstart",

    whyChooseTitle: "Warum RZK Soft wählen?",
    whyChoose1: "Experten-Team mit vielfältigen Fähigkeiten",
    whyChoose2: "Modernster Technologie-Stack",
    whyChoose3: "Agile Entwicklungsmethodik",
    whyChoose4: "Transparente Kommunikation",
    whyChoose5: "Wettbewerbsfähige Preise",

    lookingForMore: "Suchen Sie etwas Bestimmtes?",
    contactDesc: "Wir spezialisieren uns auch auf maßgeschneiderte Lösungen. Kontaktieren Sie uns, um Ihre spezifischen Anforderungen zu besprechen.",
    getInTouch: "Kontakt Aufnehmen",

    meetOurTeam: "Unser Team",
    meetOurTeamDesc: "Unser talentiertes Team aus Entwicklern, Designern und Strategen arbeitet zusammen, um außergewöhnliche Ergebnisse zu liefern.",
    rights: "Alle Rechte vorbehalten",
    footerDesc: "Wir liefern herausragende Softwareentwicklungs- und Designlösungen mit modernster Technologie und kreativer Expertise.",
    builtWith: "Erstellt mit ❤️ unter Verwendung von React, TypeScript & Tailwind CSS",

    filterAll: "Alle",
    filterDevelopers: "Entwickler",
    filterDesigners: "Designer",
    filterManagement: "Management",
    viewAllTeam: "Ganzes Team Anzeigen",

    required: "Erforderlich",
    messageSent: "Nachricht erfolgreich gesendet!",
    sendingError: "Fehler beim Senden der Nachricht. Bitte versuchen Sie es erneut.",
    sending: "Wird gesendet...",


    newsPage: 'Nachrichten',
    newsPageDesc: 'Bleiben Sie auf dem Laufenden mit den neuesten Nachrichten, Ankündigungen und Updates von RZK Soft.',
    readMore: 'Mehr lesen',
    backToNews: 'Zurück zu Nachrichten',
    publishedDate: 'Veröffentlicht',
    readTime: 'Minuten Lesezeit',
    by: 'Von',
    category: 'Kategorie',
    tags: 'Tags',
    allNews: 'Alle Nachrichten',
    companyNews: 'Unternehmensnachrichten',
    technologyNews: 'Technologie',
    teamUpdates: 'Team',
    tutorials: 'Tutorials',
    caseStudies: 'Fallstudien',
    events: 'Veranstaltungen',
    filterByCategory: 'Nach Kategorie filtern',
    searchNews: 'Nachrichten suchen...',
    noNewsFound: 'Keine Artikel gefunden.',
    shareArticle: 'Artikel teilen',
    relatedArticles: 'Verwandte Artikel',
    viewAllNews: 'Alle Nachrichten anzeigen',
  },
  nl: {
    homePage: 'Home',
    aboutUsPage: 'Over ons',
    servicesPage: 'Diensten',
    teamPage: 'Ons team',
    contactPage: 'Contact',
    companyTagline: 'Innovatieve digitale oplossingen',
    freePartLine1: 'Freelance Software',
    freePartLine2: 'Ontwikkeling & Design',
    weArePart: 'Wij zijn RZK Soft, een team van ervaren programmeurs en ontwerpers klaar om hoogwaardige oplossingen te leveren',
    hireUsPart: 'Huur ons in',
    firstPartOfBodySecondaryTextPage: 'Ons bedrijf is gespecialiseerd in hoogwaardige softwareontwikkeling en design.',
    ourServicespage: 'Onze diensten',
    webDevelopmentPage: 'Webontwikkeling',
    designPage: 'UI/UX Design',
    mobilePage: 'Mobiele ontwikkeling',
    brandingPage: 'Branding',
    aiMlPage: "AI & Machine Learning",
    devOpsPage: "DevOps & Cloud",
    consultingPage: "Technische Consultancy",
    maintenancePage: "Onderhoud & Ondersteuning",
    viewFullProfile: 'Volledig profiel bekijken',
    techStack: 'Technologieën',
    projects: 'Projecten',
    support: 'Ondersteuning',
    satisfaction: 'Satisfactie', 
    yearsExperience: 'Jaren ervaring',
    diplomasAwards: 'Diploma’s & onderscheidingen',
    viewCertificate: 'Certificaat bekijken',
    viewOnGitHub: 'Bekijk op GitHub',
    quickLinks: 'Snelle links',
    contactUs: 'Neem contact op',
    followUs: 'Volg ons',

    aboutText: "RZK Soft is een dynamisch softwareontwikkelingsbureau gespecialiseerd in het creëren van op maat gemaakte oplossingen voor bedrijven van elke omvang. Met expertise in moderne technologieën en een passie voor innovatie transformeren we ideeën in krachtige digitale ervaringen.",
    missionTitle: "Onze Missie",
    missionText: "Innovatieve softwareoplossingen leveren die bedrijven en individuen in staat stellen hun doelen te bereiken via geavanceerde technologie.",
    visionTitle: "Onze Visie",
    visionText: "Een toonaangevende wereldwijde aanbieder van softwareontwikkelingsdiensten worden, bekend om uitmuntendheid, innovatie en klanttevredenheid.",
    valuesTitle: "Onze Waarden",
    valuesText: "Kwaliteit, Innovatie, Integriteit en Klantsucces staan centraal in alles wat we doen.",

    ourProcess: "Ons Proces",
    discoveryTitle: "Ontdekking & Planning",
    discoveryText: "Begrijp vereisten en maak roadmap",
    designTitle: "Ontwerp & Prototyping",
    designText: "Wireframes en ontwerp-prototypes maken",
    developmentTitle: "Ontwikkeling",
    developmentText: "Code implementatie met agile methodologie",
    testingTitle: "Testen & Implementatie",
    testingText: "Kwaliteitsborging en productie lancering",

    whyChooseTitle: "Waarom kiezen voor RZK Soft?",
    whyChoose1: "Expertteam met diverse vaardigheden",
    whyChoose2: "Geavanceerde technologiestack",
    whyChoose3: "Agile ontwikkelingsmethodologie",
    whyChoose4: "Transparante communicatie",
    whyChoose5: "Concurrerende prijzen",

    lookingForMore: "Zoekt u iets specifieks?",
    contactDesc: "We specialiseren ons ook in maatwerkoplossingen. Neem contact met ons op om uw specifieke vereisten te bespreken.",
    getInTouch: "Neem Contact Op",

    meetOurTeam: "Ons Team",
    meetOurTeamDesc: "Ons getalenteerde team van ontwikkelaars, ontwerpers en strategen werkt samen om uitzonderlijke resultaten te leveren.",
    rights: "Alle rechten voorbehouden",
    footerDesc: "Wij leveren uitzonderlijke softwareontwikkelings- en designoplossingen met geavanceerde technologie en creatieve expertise.",
    builtWith: "Gebouwd met ❤️ met React, TypeScript & Tailwind CSS",

    filterAll: "Alle",
    filterDevelopers: "Ontwikkelaars",
    filterDesigners: "Ontwerpers",
    filterManagement: "Management",
    viewAllTeam: "Volledig Team Bekijken",

    required: "Vereist",
    messageSent: "Bericht succesvol verzonden!",
    sendingError: "Fout bij verzenden van bericht. Probeer het opnieuw.",
    sending: "Verzenden...",



    newsPage: 'Nieuws',
    newsPageDesc: 'Blijf op de hoogte van het laatste nieuws, aankondigingen en updates van RZK Soft.',
    readMore: 'Lees meer',
    backToNews: 'Terug naar nieuws',
    publishedDate: 'Gepubliceerd',
    readTime: 'min lezen',
    by: 'Door',
    category: 'Categorie',
    tags: 'Tags',
    allNews: 'Alle nieuws',
    companyNews: 'Bedrijfsnieuws',
    technologyNews: 'Technologie',
    teamUpdates: 'Team',
    tutorials: 'Handleidingen',
    caseStudies: 'Case studies',
    events: 'Evenementen',
    filterByCategory: 'Filter op categorie',
    searchNews: 'Nieuws zoeken...',
    noNewsFound: 'Geen nieuwsartikelen gevonden.',
    shareArticle: 'Artikel delen',
    relatedArticles: 'Gerelateerde artikelen',
    viewAllNews: 'Bekijk alle nieuws',
  }
};


export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('selectedLang') as Language;
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('selectedLang', language);
  }, [language]);

  const translations = allTranslations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
